# Generated by Django 4.2 on 2023-04-27 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='ISBN must be entered in the format: 9999999999.', regex='^\\d{9}[\\d|X]$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_of_publication',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
