# Generated by Django 4.2 on 2023-04-26 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='ISBN must be entered in the format: 9999999999.', regex='\\d{10}$')])),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year_of_publication', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2023)])),
                ('publisher', models.CharField(max_length=100)),
                ('image_URL_S', models.URLField()),
                ('image_URL_M', models.URLField()),
                ('image_URL_L', models.URLField()),
            ],
        ),
    ]
